/***************************************************************************************************
**                                              ˵��
**   该文件主要是定义所有项目中会用到一些宏， 
**  如果某个项目的用到配置与这里定义的不一样，请
**   在项目私有目录下的gpio_prod_table_cus_xxxx.h文件中重新定义，记住，是重新定义，所有这里是要有一个默
**   认的定义供其他项目使用的，至于如何重新定义，请参考gpio_prod_table_cus_xxxx.h中的说明，谢谢

**
***************************************************************************************************/
#ifdef __PINMAP_CONFIG__

#ifdef TOUCHPANEL_TYPE_MULTITP
//| Pin Register                                        | IO | PU/PD| Func Select| 
#define PIN_SDMMC1_CLK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//TF_SD0_CLK0
//analog_reg pin                                        | drv strength | smitt energy | input enable
#define  ANALOG_PIN_SDMMC1_OTHERS_CFG_VALUE			    (ANALOG_PIN_SDMMC1_CLK_DRV(1)) 

#if 0//def GPIO_SIMULATE_CTP_I2C
#define  PIN_SDMMC1_CMD_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//TF_SD0_CMD
#define  ANALOG_PIN_SDMMC1_OTHERS_CFG_VALUE1			(ANALOG_PIN_SDMMC1_CMD_DRV(1) | ANALOG_PIN_SDMMC1_CMD_SPU | ANALOG_PIN_SDMMC1_CMD_IE) 
#define  PIN_SDMMC1_DATA_0_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//TF_SD0_D0  
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE				(ANALOG_PIN_SDMMC1_DATA_0_DRV(1) | ANALOG_PIN_SDMMC1_DATA_0_SPU | ANALOG_PIN_SDMMC1_DATA_0_IE) 
#else
#define  PIN_SDMMC1_CMD_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(3))	//TF_SD0_CMD
#define  ANALOG_PIN_SDMMC1_OTHERS_CFG_VALUE1			(ANALOG_PIN_SDMMC1_CMD_DRV(1) | ANALOG_PIN_SDMMC1_CMD_SPU | ANALOG_PIN_SDMMC1_CMD_IE) 
#define  PIN_SDMMC1_DATA_0_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(3))	//TF_SD0_D0  
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE				(ANALOG_PIN_SDMMC1_DATA_0_DRV(1) | ANALOG_PIN_SDMMC1_DATA_0_SPU | ANALOG_PIN_SDMMC1_DATA_0_IE) 
#endif

#define  PIN_SDMMC1_DATA_1_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//TF_SD0_D1  GPIO26
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE1				(ANALOG_PIN_SDMMC1_DATA_1_DRV(7) | ANALOG_PIN_SDMMC1_DATA_1_SPU | ANALOG_PIN_SDMMC1_DATA_1_IE) 
#define  PIN_SDMMC1_DATA_2_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//TF_SD0_D2   GPIO27 
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE2				(ANALOG_PIN_SDMMC1_DATA_2_DRV(1) | ANALOG_PIN_SDMMC1_DATA_2_SPU | ANALOG_PIN_SDMMC1_DATA_2_IE)

#define  PIN_SDMMC1_DATA_3_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//TF_SD0_D3  
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE3				(ANALOG_PIN_SDMMC1_DATA_3_DRV(1) | ANALOG_PIN_SDMMC1_DATA_3_SPU | ANALOG_PIN_SDMMC1_DATA_3_IE) 

#else

//| Pin Register                                        | IO | PU/PD| Func Select| 
#define PIN_SDMMC1_CLK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//TF_SD0_CLK0
//analog_reg pin                                        | drv strength | smitt energy | input enable
#define  ANALOG_PIN_SDMMC1_OTHERS_CFG_VALUE			    (ANALOG_PIN_SDMMC1_CLK_DRV(5)) 
  
#define  PIN_SDMMC1_CMD_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//TF_SD0_CMD
#define  ANALOG_PIN_SDMMC1_OTHERS_CFG_VALUE1			(ANALOG_PIN_SDMMC1_CMD_DRV(5) | ANALOG_PIN_SDMMC1_CMD_SPU | ANALOG_PIN_SDMMC1_CMD_IE) 
#define  PIN_SDMMC1_DATA_0_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//TF_SD0_D0  
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE				(ANALOG_PIN_SDMMC1_DATA_0_DRV(5) | ANALOG_PIN_SDMMC1_DATA_0_SPU | ANALOG_PIN_SDMMC1_DATA_0_IE) 
#define  PIN_SDMMC1_DATA_1_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//TF_SD0_D1 
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE1				(ANALOG_PIN_SDMMC1_DATA_1_DRV(5) | ANALOG_PIN_SDMMC1_DATA_1_SPU | ANALOG_PIN_SDMMC1_DATA_1_IE) 
#define  PIN_SDMMC1_DATA_2_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//TF_SD0_D2  
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE2				(ANALOG_PIN_SDMMC1_DATA_2_DRV(5) | ANALOG_PIN_SDMMC1_DATA_2_SPU | ANALOG_PIN_SDMMC1_DATA_2_IE) 
#define  PIN_SDMMC1_DATA_3_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//TF_SD0_D3  
#define  ANALOG_PIN_SDMMC1_DATA_CFG_VALUE3				(ANALOG_PIN_SDMMC1_DATA_3_DRV(5) | ANALOG_PIN_SDMMC1_DATA_3_SPU | ANALOG_PIN_SDMMC1_DATA_3_IE) 
#endif

#define  PIN_ADI_SDA_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//ADI_SDA  
#define  ANALOG_PIN_ADI_CFG_VALUE						(ANALOG_PIN_ADI_SDA_DRV(1) | ANALOG_PIN_ADI_SDA_IE) 
#define  PIN_ADI_SYNC_CFG_REG_VALUE					    (PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_ADI_CFG_VALUE1						(ANALOG_PIN_ADI_SYNC_DRV(1)) 
#define  PIN_ADI_SCL_CFG_REG_VALUE						(PIN_IO_DEFAULT) | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0)	//ADC_SCL  
#define  ANALOG_PIN_ADI_CFG_VALUE2						(ANALOG_PIN_ADI_SCL_DRV(1)) 
#define  PIN_SPI_LCD_SIO_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//LCM_SPI_DIO
#define  ANALOG_PIN_SPI_LCD_CFG2_VALUE					(ANALOG_PIN_SPI_LCD_SIO_DRV(2) | ANALOG_PIN_SPI_LCD_SIO_IE) 
#define  PIN_SPI_LCD_SDC_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//LCM_SPI_RS  
#define  ANALOG_PIN_SPI_LCD_CFG2_VALUE1				    (ANALOG_PIN_SPI_LCD_SDC_DRV(2)) 
#define  PIN_SPI_LCD_CLK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//LCM_SPI_CLK  
#define  ANALOG_PIN_SPI_LCD_CFG1_VALUE					(ANALOG_PIN_SPI_LCD_CLK_DRV(2)) 
#define  PIN_SPI_LCD_CS_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//LCM_SPI_CSN  
#define  ANALOG_PIN_SPI_LCD_CFG1_VALUE2				    (ANALOG_PIN_SPI_LCD_CS_DRV(2)) 
#define  PIN_SPI_LCD_SELECT_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_SPI_LCD_CFG2_VALUE2				    (ANALOG_PIN_SPI_LCD_SELECT_DRV(2)) 
#define  PIN_LCD_FMARK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//LCM_FMARK  
#define  ANALOG_PIN_LCD_CFG_VALUE						(ANALOG_PIN_LCD_FMARK_DRV(2) | ANALOG_PIN_LCD_FMARK_IE) 
#define  PIN_LCD_RSTB_CFG_REG_VALUE					    (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//LCM_RSTN  
#define  ANALOG_PIN_LCD_CFG_VALUE2						(ANALOG_PIN_LCD_RSTB_DRV(2)) 
#define  PIN_I2C_M1_SCL_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//CAM_I2C_SCL 
#define  ANALOG_PIN_I2C_CFG_VALUE						(ANALOG_PIN_I2C_M1_SCL_DRV(1) | ANALOG_PIN_I2C_M1_SCL_WPUS | ANALOG_PIN_I2C_M1_SCL_IE) 
#define  PIN_I2C_M1_SDA_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//CAM_I2C_SDA  
#define  ANALOG_PIN_I2C_CFG_VALUE2						(ANALOG_PIN_I2C_M1_SDA_DRV(1) | ANALOG_PIN_I2C_M1_SDA_WPUS | ANALOG_PIN_I2C_M1_SDA_IE) 
#define  PIN_CAMERA_RST_L_CFG_REG_VALUE				    (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//CAM_RST  
#define  ANALOG_PIN_CAMERA_CFG_VALUE					(ANALOG_PIN_CAMERA_RST_L_DRV(1)) 
#define  PIN_CAMERA_PWDN_CFG_REG_VALUE				    (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//CAM_PWDN  
#define  ANALOG_PIN_CAMERA_CFG_VALUE2					(ANALOG_PIN_CAMERA_PWDN_DRV(1)) 
#define  PIN_CAMERA_REF_CLK_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//CAM_MCLK  
#define  ANALOG_PIN_CAMERA_CFG_VALUE3					(ANALOG_PIN_CAMERA_REF_CLK_DRV(1)) 
#define  PIN_SPI_CAMERA_SI_0_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//SPI_CAMERA_SI_0 
#define  ANALOG_PIN_SPI_CAMERA_CFG_VALUE				(ANALOG_PIN_SPI_CAMERA_SI_0_DRV(1) | ANALOG_PIN_SPI_CAMERA_SI_0_IE) 
#define  PIN_SPI_CAMERA_SI_1_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//SPI_CAMERA_SI_1
#define  ANALOG_PIN_SPI_CAMERA_CFG_VALUE1				(ANALOG_PIN_SPI_CAMERA_SI_1_DRV(1) | ANALOG_PIN_SPI_CAMERA_SI_1_IE) 
#define  PIN_SPI_CAMERA_SCK_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//SPI_CAMERA_SCK  
#define  ANALOG_PIN_SPI_CAMERA_CFG_VALUE2				(ANALOG_PIN_SPI_CAMERA_SCK_DRV(1) | ANALOG_PIN_SPI_CAMERA_SCK_IE) 
#define  PIN_GPIO_13_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0)) 	//NC (TB2103) 
#define  ANALOG_PIN_GPIO13_CFG_VALUE					(ANALOG_PIN_GPIO_13_DRV(1) | ANALOG_PIN_GPIO_13_IE) 
#define  PIN_GPIO_7_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//gpio06--ANA_INT 
#define  ANALOG_PIN_GPIO_CFG2_VALUE					    (ANALOG_PIN_GPIO_7_DRV(1)) 
#define  PIN_AP_JTAG_TCK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//MTCK  
#define  ANALOG_PIN_AP_JTAG_CFG_VALUE					(ANALOG_PIN_AP_JTAG_TCK_DRV(1) | ANALOG_PIN_AP_JTAG_TCK_WPUS | ANALOG_PIN_AP_JTAG_TCK_IE) 
#define  PIN_AP_JTAG_TRST_CFG_REG_VALUE				    (PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_AP_JTAG_CFG_VALUE1					(ANALOG_PIN_AP_JTAG_TRST_DRV(1) | ANALOG_PIN_AP_JTAG_TRST_WPUS | ANALOG_PIN_AP_JTAG_TRST_IE) 
#define  PIN_AP_JTAG_TMS_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//MTMS  
#define  ANALOG_PIN_AP_JTAG_CFG_VALUE2					(ANALOG_PIN_AP_JTAG_TMS_DRV(1) | ANALOG_PIN_AP_JTAG_TMS_WPUS | ANALOG_PIN_AP_JTAG_TMS_IE) 
#define  PIN_AP_JTAG_TDI_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_AP_JTAG_CFG_VALUE3					(ANALOG_PIN_AP_JTAG_TDI_DRV(1) | ANALOG_PIN_AP_JTAG_TDI_WPUS | ANALOG_PIN_AP_JTAG_TDI_IE) 
#define  PIN_AP_JTAG_TDO_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_AP_JTAG_CFG_VALUE4					(ANALOG_PIN_AP_JTAG_TDO_DRV(1) | ANALOG_PIN_AP_JTAG_TDO_WPUS) 
#define  PIN_GPIO_14_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//I2C_M2_SCL  
#define  ANALOG_PIN_I2C_CFG_VALUE1						(ANALOG_PIN_GPIO_14_DRV(1) | ANALOG_PIN_GPIO_14_WPUS | ANALOG_PIN_GPIO_14_IE) 
#define  PIN_GPIO_15_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//I2C_M2_SDA  
#define  ANALOG_PIN_I2C_CFG_VALUE2						(ANALOG_PIN_GPIO_15_DRV(1) | ANALOG_PIN_GPIO_15_WPUS | ANALOG_PIN_GPIO_15_IE) 
#define  PIN_GPIO_18_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(3))	//UART1_CTS
#define  ANALOG_PIN_UART_1_CFG_VALUE					(ANALOG_PIN_GPIO_18_DRV(1)) 
#define  PIN_GPIO_19_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(3))	//UART1_RTS  
#define  ANALOG_PIN_UART_1_CFG_VALUE2					(ANALOG_PIN_GPIO_19_DRV(1)) 
#if defined(MOS_SUPPORT)
#define  PIN_GPIO_20_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//UART2_RXD  
#define  ANALOG_PIN_UART_2_CFG_VALUE					(ANALOG_PIN_GPIO_20_DRV(1) | ANALOG_PIN_GPIO_20_IE) 
#define  PIN_GPIO_21_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(1))	//UART2_TXD  
#define  ANALOG_PIN_UART_2_CFG_VALUE1					(ANALOG_PIN_GPIO_21_DRV(1)) 
#define  PIN_GPIO_22_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(1))	//UART2_CTS  
#define  ANALOG_PIN_UART_2_CFG_VALUE2					(ANALOG_PIN_GPIO_22_DRV(1) | ANALOG_PIN_GPIO_22_IE) 
#define  PIN_GPIO_23_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(1))	//UART2_RTS  
#define  ANALOG_PIN_UART_2_CFG_VALUE3					(ANALOG_PIN_GPIO_23_DRV(1)) 
#else
#define  PIN_GPIO_20_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//UART3_RXD  
#define  ANALOG_PIN_UART_2_CFG_VALUE					(ANALOG_PIN_GPIO_20_DRV(1) | ANALOG_PIN_GPIO_20_IE) 
#define  PIN_GPIO_21_CFG_REG_VALUE						(PIN_IN_FRC     | PIN_PULL_FRC_UP | PIN_FUNC_SEL(1))	//UART3_TXD  
#define  ANALOG_PIN_UART_2_CFG_VALUE1					(ANALOG_PIN_GPIO_21_DRV(1)) 
#define  PIN_GPIO_22_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(2))	//UART3_CTS  
#define  ANALOG_PIN_UART_2_CFG_VALUE2					(ANALOG_PIN_GPIO_22_DRV(1) | ANALOG_PIN_GPIO_22_IE) 
#define  PIN_GPIO_23_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(2))	//UART3_RTS  
#define  ANALOG_PIN_UART_2_CFG_VALUE3					(ANALOG_PIN_GPIO_23_DRV(1)) 
#endif
#define  PIN_GPIO_9_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_GPO_CFG_VALUE						(ANALOG_PIN_GPIO_9_DRV(1)) 
#define  PIN_GPIO_10_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))//MTMS  
#define  ANALOG_PIN_GPO_CFG_VALUE1						(ANALOG_PIN_GPIO_10_DRV(1)) 
#define  PIN_GPIO_11_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_GPO_CFG_VALUE2						(ANALOG_PIN_GPIO_11_DRV(1)) 
#define  PIN_GPIO_12_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_GPO_CFG_VALUE3						(ANALOG_PIN_GPIO_12_DRV(1)) 
#define  PIN_KEYIN_0_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//KEYIN0  
#define  ANALOG_PIN_KEYIN_CFG_VALUE					    (ANALOG_PIN_KEYIN_0_DRV(1) | ANALOG_PIN_KEYIN_0_IE) 
#define  PIN_KEYIN_1_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//KEYIN1  
#define  ANALOG_PIN_KEYIN_CFG_VALUE1					(ANALOG_PIN_KEYIN_1_DRV(1) | ANALOG_PIN_KEYIN_1_IE) 
#define  PIN_KEYIN_2_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//KEYIN2  
#define  ANALOG_PIN_KEYIN_CFG_VALUE2					(ANALOG_PIN_KEYIN_2_DRV(1) | ANALOG_PIN_KEYIN_2_IE) 
#define  PIN_KEYIN_3_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//KEYIN3  
#define  ANALOG_PIN_KEYIN_CFG_VALUE3					(ANALOG_PIN_KEYIN_3_DRV(1) | ANALOG_PIN_KEYIN_3_IE) 
#define  PIN_KEYIN_4_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//KEYIN4  
#define  ANALOG_PIN_KEYIN_CFG_VALUE4					(ANALOG_PIN_KEYIN_4_DRV(1) | ANALOG_PIN_KEYIN_4_IE) 
#define  PIN_KEYIN_5_CFG_REG_VALUE						(PIN_IO_DEFAULT | PIN_PULL_FRC_DN | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_KEYIN_CFG_VALUE5					(ANALOG_PIN_KEYIN_5_DRV(1)) 
#define  PIN_KEYOUT_0_CFG_REG_VALUE                     (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//KEYOUT0  
#define  ANALOG_PIN_KEYOUT_CFG_VALUE					(ANALOG_PIN_KEYOUT_0_DRV(1)) 
#define  PIN_KEYOUT_1_CFG_REG_VALUE                     (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//KEYOUT1  
#define  ANALOG_PIN_KEYOUT_CFG_VALUE1					(ANALOG_PIN_KEYOUT_1_DRV(1)) 
#define  PIN_KEYOUT_2_CFG_REG_VALUE                     (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//KEYOUT2  
#define  ANALOG_PIN_KEYOUT_CFG_VALUE2					(ANALOG_PIN_KEYOUT_2_DRV(1)) 
#define  PIN_KEYOUT_3_CFG_REG_VALUE					    (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//KEYOUT3  
#define  ANALOG_PIN_KEYOUT_CFG_VALUE3					(ANALOG_PIN_KEYOUT_3_DRV(1)) 
#define  PIN_KEYOUT_4_CFG_REG_VALUE					    (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//KEYOUT4  
#define  ANALOG_PIN_KEYOUT_CFG_VALUE4					(ANALOG_PIN_KEYOUT_4_DRV(1)) 
#define  PIN_KEYOUT_5_CFG_REG_VALUE                     (PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//NC  
#define  ANALOG_PIN_KEYOUT_CFG_VALUE5					(ANALOG_PIN_KEYOUT_5_DRV(1)) 
#define  PIN_DEBUG_HOST_RX_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))//DBG_HOST_RX  
#define  ANALOG_PIN_DEBUG_HOST_CFG_VALUE				(ANALOG_PIN_DEBUG_HOST_RX_DRV(1) | ANALOG_PIN_DEBUG_HOST_RX_IE) 
#define  PIN_DEBUG_HOST_TX_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))//DBG_HOST_TX  
#define  ANALOG_PIN_DEBUG_HOST_CFG_VALUE1				(ANALOG_PIN_DEBUG_HOST_TX_DRV(1)) 
#define  PIN_DEBUG_HOST_CLK_CFG_REG_VALUE				(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))//NC  
#define  ANALOG_PIN_DEBUG_HOST_CFG_VALUE2				(ANALOG_PIN_DEBUG_HOST_CLK_DRV(1)  | ANALOG_PIN_DEBUG_HOST_CLK_IE) 
#define  PIN_SIM_1_CLK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//SIM0_CLK  
#define  ANALOG_PIN_SIM_1_CFG_VALUE					    (ANALOG_PIN_SIM_1_CLK_DRV(1)) 
#define  PIN_SIM_1_DIO_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//SIM0_DA  frc=1 up=0 dn=0 spu=1 4.7K_up
#define  ANALOG_PIN_SIM_1_CFG_VALUE1					(ANALOG_PIN_SIM_1_DIO_DRV(1) | ANALOG_PIN_SIM_1_DIO_SPU | ANALOG_PIN_SIM_1_DIO_IE) 
#define  PIN_SIM_1_RST_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//SIM0_RST  
#define  ANALOG_PIN_SIM_1_CFG_VALUE2					(ANALOG_PIN_SIM_1_RST_DRV(1)) 
#define  PIN_SIM_2_CLK_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//SIM1_CLK  
#define  ANALOG_PIN_SIM_2_CFG_VALUE					    (ANALOG_PIN_SIM_2_CLK_DRV(1)) 
#define  PIN_SIM_2_DIO_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_NONE | PIN_FUNC_SEL(0))	//SIM1_DA  frc=1 up=0 dn=0 spu=1 4.7K_up
#define  ANALOG_PIN_SIM_2_CFG_VALUE1					(ANALOG_PIN_SIM_2_DIO_DRV(1) | ANALOG_PIN_SIM_2_DIO_SPU | ANALOG_PIN_SIM_2_DIO_IE) 
#define  PIN_SIM_2_RST_CFG_REG_VALUE					(PIN_IO_DEFAULT | PIN_PULL_FRC_DEFAULT | PIN_FUNC_SEL(0))	//SIM1_RST  
#define  ANALOG_PIN_SIM_2_CFG_VALUE2					(ANALOG_PIN_SIM_2_RST_DRV(1)) 
#endif //__PINMAP_CONFIG__



#ifdef __PM_GPIO_DEFAULT_MAP__
//         macro                              |  NO. | Def Valule  |     Direct           |   INT Sense      |    
#define PM_GPIO_DEFAULT_0
#define PM_GPIO_DEFAULT_1
#define PM_GPIO_DEFAULT_2
#define PM_GPIO_DEFAULT_3               
#define PM_GPIO_DEFAULT_4
#define PM_GPIO_DEFAULT_5          
#define PM_GPIO_DEFAULT_6        {6,      0,     PM_INPUT,      PM_LEVEL },
#define PM_GPIO_DEFAULT_7        {7,      1,     PM_OUTPUT,     PM_NO_INT},
#define PM_GPIO_DEFAULT_8
#define PM_GPIO_DEFAULT_9
#define PM_GPIO_DEFAULT_10       {10,     0,     PM_OUTPUT,     PM_NO_INT},

#define PM_GPIO_DEFAULT_11
#define PM_GPIO_DEFAULT_12       {12,     0,     PM_OUTPUT,     PM_NO_INT},
#define PM_GPIO_DEFAULT_13
#define PM_GPIO_DEFAULT_14
#define PM_GPIO_DEFAULT_15
#define PM_GPIO_DEFAULT_16
#define PM_GPIO_DEFAULT_17   
#define PM_GPIO_DEFAULT_18
#define PM_GPIO_DEFAULT_19    
#define PM_GPIO_DEFAULT_20

#define PM_GPIO_DEFAULT_21          
#define PM_GPIO_DEFAULT_22          
#define PM_GPIO_DEFAULT_23 
#ifdef TOUCHPANEL_TYPE_MULTITP
#if 0//def GPIO_SIMULATE_CTP_I2C
#define PM_GPIO_DEFAULT_24     {24,      1,     PM_OUTPUT,      PM_NO_INT },
#define PM_GPIO_DEFAULT_25     {25,      1,     PM_OUTPUT,      PM_NO_INT },
#endif
#define PM_GPIO_DEFAULT_26     {26,      1,     PM_INPUT,       PM_LEVEL  },
#define PM_GPIO_DEFAULT_27     {27,      0,     PM_OUTPUT,      PM_NO_INT },
#else
#define PM_GPIO_DEFAULT_24
#define PM_GPIO_DEFAULT_25

#define PM_GPIO_DEFAULT_26    
#define PM_GPIO_DEFAULT_27   
#endif
#define PM_GPIO_DEFAULT_28
#define PM_GPIO_DEFAULT_29
#define PM_GPIO_DEFAULT_30

#define PM_GPIO_DEFAULT_31
#define PM_GPIO_DEFAULT_32
#endif //__PM_GPIO_DEFAULT_MAP__

#ifdef __S_GPIO_PROD_CFG_CUS_TABLE__
/*macro                                                ID                              TYPE             VALID_LEVEL                   NUM.                      CALLBACK    */
#define GPIO_PROD_LCD_BL_EN_ID_CFG          {GPIO_PROD_LCD_BL_EN_ID,			GPIO_PROD_TYPE_MAX, GPIO_PROD_HIGH_LEVEL,	   GPIO_PROD_NUM_INVALID,	 _GPIO_OpenLCMBackLight },
#define GPIO_PROD_KEYPAD_BL_ID_CFG          {GPIO_PROD_KEYPAD_BL_ID,            GPIO_PROD_TYPE_MAX, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    _GPIO_OpenKeyPadBackLight },
#define GPIO_PROD_VIBRATIOR_EN_ID_CFG       {GPIO_PROD_VIBRATIOR_EN_ID,         GPIO_PROD_TYPE_MAX, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    _GPIO_OpenVibrator }, 
#define GPIO_PROD_FLASH_EN_ID_CFG           {GPIO_PROD_FLASH_EN_ID,             GPIO_PROD_TYPE_MAX, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    _GPIO_OpenFlashLight },  
#define GPIO_PROD_HEADSET_BUTTON_ID_CFG     {GPIO_PROD_HEADSET_BUTTON_ID,       GPIO_PROD_TYPE_EIC_DBNC, GPIO_PROD_HIGH_LEVEL, EICA_AUD_HEAD_BUTTON,     PNULL },
#define GPIO_PROD_HEADSET_DETECT_ID_CFG     {GPIO_PROD_HEADSET_DETECT_ID,       GPIO_PROD_TYPE_EIC_DBNC, GPIO_PROD_HIGH_LEVEL, EIC_AUD_HEAD_INSERT_ALL,  PNULL },
#define GPIO_PROD_SENSOR_RESET_ID_CFG       {GPIO_PROD_SENSOR_RESET_ID,         GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      53,                       PNULL },
#define GPIO_PROD_SENSOR_PWDN_ID_CFG        {GPIO_PROD_SENSOR_PWDN_ID,          GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      52,                       PNULL },  
#define GPIO_PROD_SENSOR_POWER_ID_CFG       {GPIO_PROD_SENSOR_POWER_ID,         GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    PNULL }, 
#define GPIO_PROD_CHARGE_PLUG_DETECT_ID_CFG {GPIO_PROD_CHARGE_PLUG_DETECT_ID,   GPIO_PROD_TYPE_EIC_DBNC, GPIO_PROD_HIGH_LEVEL, EICA_CHGR_INT,            PNULL },
#define GPIO_PROD_POWER_KEY_ID_CFG          {GPIO_PROD_POWER_KEY_ID,            GPIO_PROD_TYPE_EIC_DBNC, GPIO_PROD_LOW_LEVEL,  EICA_PBINT,               PNULL }, 
#define GPIO_PROD_BATTERY_DETECT_ID_CFG     {GPIO_PROD_BATTERY_DETECT_ID,       GPIO_PROD_TYPE_EIC_DBNC, GPIO_PROD_HIGH_LEVEL, EICA_BATDET_OK,           PNULL },
#define GPIO_PROD_SPEAKER_PA_EN_ID_CFG      {GPIO_PROD_SPEAKER_PA_EN_ID,        GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    (GPIO_CB)_GPIO_OpenPA },
#define GPIO_PROD_BT_RESET_ID_CFG           {GPIO_PROD_BT_RESET_ID,             GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    PNULL },
#define GPIO_PROD_GSENSOR_INT_ID_CFG        {GPIO_PROD_GSENSOR_INT_ID,          GPIO_PROD_TYPE_BB0, GPIO_PROD_LOW_LEVEL,       GPIO_PROD_NUM_INVALID,    (GPIO_CB)MSensor_IntHandler },
#define GPIO_PROD_SIM_PLUG_IN_ID_CFG        {GPIO_PROD_SIM_PLUG_IN_ID,			GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,	   49,                       PNULL },
#define GPIO_PROD_WIFI_PWD_ID_CFG           {GPIO_PROD_WIFI_PWD_ID,             GPIO_PROD_TYPE_BB0, GPIO_PROD_LOW_LEVEL,       29 ,                      PNULL },
#define GPIO_PROD_WIFI_INT_ID_CFG           {GPIO_PROD_WIFI_INT_ID,             GPIO_PROD_TYPE_BB0, GPIO_PROD_LOW_LEVEL,       47,                       (GPIO_CB)WIFI_IrqCallback },
#define GPIO_PROD_USB_DETECT_ID_CFG         {GPIO_PROD_USB_DETECT_ID,           GPIO_PROD_TYPE_MAX, GPIO_PROD_HIGH_LEVEL,      GPIO_PROD_NUM_INVALID,    _GPIO_IsUsbOrAdapter },
#define GPIO_PROD_2720_INT_ID_CFG           {GPIO_PROD_2720_INT_ID,             GPIO_PROD_TYPE_BB0, GPIO_PROD_LOW_LEVEL,       6 ,                       PNULL },
#define GPIO_PROD_CALIB_SEL_ID_CFG          {GPIO_PROD_CALIB_SEL_ID,            GPIO_PROD_TYPE_BB0, GPIO_PROD_LOW_LEVEL,       13 ,                      PNULL },

#if defined(GPS_CHIP_SUPPORT_AT6558R) || defined(GPS_CHIP_AT6558R_DEBUG)
#define GPIO_PROD_GPS_LDO_EN_ID_CFG         {GPIO_PROD_GPS_LDO_EN_ID,           GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      10 ,                      PNULL },
#define GPIO_PROD_GPS_LNA_EN_ID_CFG         {GPIO_PROD_GPS_LNA_EN_ID,           GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,      12 ,                      PNULL },
#endif

#ifdef TOUCHPANEL_TYPE_MULTITP
#if 0//def GPIO_SIMULATE_CTP_I2C
#define GPIO_PROD_TP_SCL_ID_CFG             {GPIO_PROD_TP_SCL_ID,              GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,       24 ,                       PNULL },
#define GPIO_PROD_TP_SDA_ID_CFG             {GPIO_PROD_TP_SDA_ID,              GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,       25 ,                       PNULL },
#endif

#define GPIO_PROD_TP_INT_ID_CFG             {GPIO_PROD_TP_INT_ID,               GPIO_PROD_TYPE_BB0, GPIO_PROD_LOW_LEVEL,       26 ,                       PNULL },
#define GPIO_PROD_TP_WAKE_ID_CFG            {GPIO_PROD_TP_WAKE_ID,              GPIO_PROD_TYPE_BB0, GPIO_PROD_HIGH_LEVEL,       27 ,                       PNULL },
#endif

#endif // __S_GPIO_PROD_CFG_CUS_TABLE__

 
#ifdef __KENMAP_CONFIG__
// COL 0
#define	KEYIN0_KEYOUT0   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT1   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT2   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT3   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT4   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT5   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT6   SCI_VK_INVALID_KEY,
#define	KEYIN0_KEYOUT7   SCI_VK_INVALID_KEY, 
// COL 1
#define	KEYIN1_KEYOUT0   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT1   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT2   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT3   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT4   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT5   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT6   SCI_VK_INVALID_KEY,
#define	KEYIN1_KEYOUT7   SCI_VK_INVALID_KEY,
// COL 2
#define	KEYIN2_KEYOUT0   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT1   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT2   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT3   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT4   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT5   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT6   SCI_VK_INVALID_KEY,
#define	KEYIN2_KEYOUT7   SCI_VK_INVALID_KEY,
// COL 3
#define	KEYIN3_KEYOUT0   SCI_VK_INVALID_KEY,
#define	KEYIN3_KEYOUT1   SCI_VK_INVALID_KEY,    
#define	KEYIN3_KEYOUT2   SCI_VK_INVALID_KEY,
#define	KEYIN3_KEYOUT3   SCI_VK_INVALID_KEY,
#define	KEYIN3_KEYOUT4   SCI_VK_INVALID_KEY,
#define	KEYIN3_KEYOUT5   SCI_VK_INVALID_KEY,
#define	KEYIN3_KEYOUT6   SCI_VK_INVALID_KEY,
#define	KEYIN3_KEYOUT7   SCI_VK_INVALID_KEY,
// COL 4
#define	KEYIN4_KEYOUT0   SCI_VK_INVALID_KEY,
#define	KEYIN4_KEYOUT1   SCI_VK_INVALID_KEY,
#define	KEYIN4_KEYOUT2   SCI_VK_INVALID_KEY,              
#define	KEYIN4_KEYOUT3   SCI_VK_INVALID_KEY,
#define	KEYIN4_KEYOUT4   SCI_VK_INVALID_KEY,
#define	KEYIN4_KEYOUT5   SCI_VK_INVALID_KEY,
#define	KEYIN4_KEYOUT6   SCI_VK_INVALID_KEY,
#define	KEYIN4_KEYOUT7   SCI_VK_INVALID_KEY,

#ifdef TP_VK_SUPPORT
#define  TP_VIRTUAL_KEY1
#define  TP_VIRTUAL_KEY2
#define  TP_VIRTUAL_KEY3
#define  TP_VIRTUAL_KEY4
#define  TP_VIRTUAL_KEY5
#define  TP_VIRTUAL_KEY6
#endif
#endif // __KENMAP_CONFIG__

#ifdef __LCM_CONFIG_INFO__
#define MIAN_LCD_BACKLIGHT_INFO  {LCD_BACKLIGHT_TYPE_BB_ANALOG, 0,0,0}
#define SUB_LCD_BACKLIGHT_INFO   {LCD_BACKLIGHT_TYPE_BB_ANALOG, 0,0,0}
#endif

#include "custom_config_macro_project.h" //该文件是由custom_config_macro_project_xxxx.h(其中xxxx是项目名称)自动生成，请保证该行该文件的最后一行
